import Head from "next/head";
import React from "react";

export default function Home() {
    const [CatCard, setCatCard] = React.useState(null);
    React.useEffect(() => {
        if (typeof window !== 'undefined') {
            setCatCard(React.lazy(() => import('remote/CatCard')));
        }
    }, []);

  return (
    <>
      <Head>
        <title>Module federation test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{paddingLeft: "100px"}}>
          <h1>Module federation test</h1>
            <div>
                <p>Remote component: </p>
                <React.Suspense fallback={<div>Loading...</div>}>
                    {CatCard && <CatCard
                        buttonCallback={() => {
                            alert('Claimed!')
                        }}
                        rating={5}
                        imageUrl="https://cataas.com/cat"
                        name="Test cat"
                        description="This is a cute cat"
                    />}
                </React.Suspense>
                <p>The component above is a component imported with module federation</p>
                <p>This side was rendered on the server except the remote component because module federation does not support ssr on the host but only on the remote side</p>
            </div>
        </div>
      </main>
    </>
  );
}
